homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('jadwal/create', views.jadwal_create, name="jadwal_create"),
    path('jadwal/delete/<int:id>', views.jadwal_delete, name="jadwal_delete")
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class jadwalKegiatan (models.Model):
    aktivitas = models.CharField(max_length=100, default='Aktivitas')
    tanggal = models.DateField()
    jam = models.TimeField(default=datetime.now)
    tempat = models.CharField(max_length=100, default='Tempat')
    kategori = models.CharField(max_length=100, default='Other')

    def __str__(self):
        return self.aktivitas

homepage/forms.py
from django import forms
from homepage.models import jadwalKegiatan


class formKegiatan(forms.ModelForm):
    aktivitas = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, }))
    tanggal = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'required': True, }))
    jam = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'required': True, }))
    tempat = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, }))
    kategori = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': True, }))

    class Meta:
        model = jadwalKegiatan
        fields = ['aktivitas', 'tanggal', 'jam', 'tempat', 'kategori']

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

from .forms import formKegiatan
from .models import jadwalKegiatan

# Create your views here.


def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def jadwal(request):
    jadwal = jadwalKegiatan.objects.all().order_by('tanggal')
    return render(request, 'jadwal.html', {'jadwalKegiatan': jadwal})


def jadwal_create(request):
    if request.method == 'POST':
        form = formKegiatan(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/jadwal/')
    else:
        form = formKegiatan()
    return render(request, 'jadwal_create.html', {'form': form})


def jadwal_delete(request, id):
    if request.method == 'POST':
        jadwalKegiatan.objects.filter(id=id).delete()
        return HttpResponseRedirect('/jadwal/')
    else:
        return HttpResponse("GET NOT ALLOWED")

homepage/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Adit | About</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container" id="About.page">
        <div class="row">
            <div class="col">
                <div class="judul">
                        <p class="posisi">PROFILE</p>
                </div>
                <div class="isi">
                    <p>An undergraduate Information Systems
                        student at Universitas Indonesia who is
                        hard worker and fully responsible. I do
                        love to try a new challenging atmosphere.
                        Now I'm interested in information system
                        management to prepare myself to be a
                        future leader.</p>
                </div>
            </div>
            <div class="col">
                <img src="{% static 'images/Edit.jpg' %}" alt="Foto Adit">
            </div>
        </div>
    </div>
    <div class="edukasi">
        <img class="img-fluid" src="{% static 'images/rsz_90.jpg' %}" alt="Universitas Indonesia">
        <div class="top-left">
            <div class="judul2">
                <p>EDUCATION</p>
            </div>
            <div class="isi">
                <p class="posisi2">Faculty Of Computer Science</p>
                <p>Universitas Indonesia</p>
            </div>
        </div>
        <div class="skills">
            <img src="{% static 'images/rsz_chris-ried-ieic5tq8ymk-unsplash.jpg' %}" alt="Coding">
            <div class="top-right">
                <div class="judul2">
                    <p class="posisi">PROGRAMMING SKILLS</p>
                </div>
                <div class="d-flex justify-content-start">
                    <img src="{% static 'images/1200px-ISO_C++_Logo.svg.png' %}" alt="C++" class="iconSkills">
                    <img src="{% static 'images/1024px-Python-logo-notext.svg.png' %}" alt="Python" class="iconSkills">
                    <img src="{% static 'images/1200px-Java_programming_language_logo.svg.png' %}" alt="Java" class="iconSkills2">
                </div>
                <div class="explanation2">
                    <p> - Expert and Creative</p>
                </div>
            </div>
        </div>
        <div class="bottom-right">
            <p class="credits">Photo by Chris Ried on Unsplash</p>
        </div>
    </div>
    <div class="warna">
        <div class="judul2">
            <p>EXPERIENCES AND ORGANIZATIONS</p>
        </div>
        <div class="isi">
            <p class="posisi2">Staff of Art Department BEM Fasilkom UI</p>
            <p class="explanation">"2019 - Staff of student council that accommodates art in Fasilkom UI"</p>
            <p class="posisi2">Staff of Human Reaserch Development Compfest</p>
            <p class="explanation">"2019 - Staff of HRD Compfest that manages staff Equipment and Security division"</p>
            <p class="posisi2">Staff of Event Computer Science League</p>
            <p class="explanation">“2019 - Staff of Event CSL that programs event in CSL such as rundown and match report"</p>
            <p class="posisi2">Staff of Public Relations and Publication Open House Fasilkom UI</p>
            <p class="explanation">“2018 - Staff of PR that spreads OH Fasilkom to highschool student and introduces Fasilkom to HS student”</p>
        </div>
    </div>
    </div>
    <div class="container-fluid">
        <div class="contact">
            <div class="d-flex flex-row bd-highlight mb-3">
                <div class="p-2 bd-highlight">
                    <p class="judul3">CONTACT ME</p>
                </div>
                <div class="p-2 bd-highlight">
                    <div class="vl"></div>
                </div>
                <div class="p-2 bd-highlight">
                    <div class="isi">
                        <p class="posisi3">aditmuhammad06@gmail.com</p>
                    </div>
                </div>
                <div class="p-2 bd-highlight" style="display: flex">
                    <a href="https://facebook.com/aditmuhmd"><img src="{% static 'images/icons8-facebook-circled-96.png' %}" alt="Facebook Icon" class="iconMargin"></a>
                    <a href="https://twitter.com/aditmuhmd"><img src="{% static 'images/icons8-twitter-96.png' %}" alt="Twitter Icon" class="iconMargin"></a>
                    <a href="https://linkedin.com/in/aditmuhmd"><img src="{% static 'images/icons8-linkedin-96.png' %}" alt="Linkedin Icon" class="iconMargin"></a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Adit | Index</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="containter-fluid index">
        <div class="row">
            <div class="col-sm placement">
                <div class="judul">
                    <p>WELCOME TO MY SITE</p>
                </div>
                <div class="isi">
                    <p>Muhammad Aditya</p>
                    <a href="{% url 'homepage:about' %}">
                        <button type="button" class="btn btn-aboutme btn-outline-dark">About Me</button>
                    </a>
            </div>
            <div class="col-sm">
                <p class="credits">Photo by NordWood Themes on Unsplash</p>
            </div>
        </div>
    </div>
</body>
</html>

homepage/templates/jadwal.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Adit | Activity</title>
</head>
<body>
    {% include "navbar.html" %}
    <h1 style="text-align: center;">
        JADWAL KEGIATAN
    </h1>
    <div class="containter">
        <div class="row">
            {% for jadwal in jadwalKegiatan %}
                <div class="col-sm-4 text-center">
                    <h2>{{ jadwal.aktivitas }}</h2>
                    <p>{{ jadwal.tanggal }}</p>
                    <p>{{ jadwal.jam }}</p>
                    <p>{{ jadwal.tempat }}</p>
                    <p>{{ jadwal.kategori }}</p>
                    <form action="delete/{{ jadwal.id }}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-warning">Delete</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
</body>

homepage/templates/jadwal_create.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Adit | Isi Kegiatan</title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container" style="padding: 30px">
        <h1 style="text-align: center;">
            Isi Jadwal Kegiatan
        </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-success" value="Add">Submit</button>
        </form>
    </div>
</body>
</html>

homepage/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <img style="height:50px" src="{% static 'img/logo.png' %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:index' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:jadwal_create' %}">Isi Kegiatan</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:jadwal' %}">Jadwal Kegiatan</a>
        </li>
        </ul>
    </div>
</nav>

homepage/templates/thanks.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
</head>
<body style="padding: 50px">
    <div class="container">
        <h1>
            Terima Kasih sudah mengisi jadwal kegiatan!! <br>
            Untuk jadwal kegiatan, klik <a href="{% url 'homepage:jadwal' %}">ini</a>
        </h1>
    </div>
</body>